# Generated by Django 3.2.8 on 2021-10-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211028_1930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='SubCategory',
        ),
    ]
